### ISSUE TITLE
Does not return countries data

### ISSUE THREAD

**Issue by palashkaria** [gilmoreorless/moment-timezone-data-webpack-plugin#22]
`countries` is an empty array, and there's no way to pass the same currently
(see cache screenshot)

The problem is in this L30 in index.js, where we pass only `zones` and `version` while creating the data.
https://github.com/gilmoreorless/moment-timezone-data-webpack-plugin/blob/master/src/index.js#L30

Should there be an option to pass country data too? 

![image](https://user-images.githubusercontent.com/2976363/77823271-cfa76380-711f-11ea-9ed1-67c4b2f88602.png)

**Comment by gilmoreorless** [comment]
Thanks for raising this! The adding of country data to the API only happened in the most recent release of `moment-timezone` (0.5.28, although [there's some confusion about the exact version](https://github.com/moment/moment-timezone/issues/827)) — so it's not yet accounted for by this plugin.

I'll take a look into adding filtered country data as well.

**Comment by gilmoreorless** [comment]
The fix for this is now available in version `1.2.0`.

**Comment by palashkaria** [comment]
Thanks a lot, this works perfectly for my use case! I had created a local copy of the plugin which I can delete now 😄
