### ISSUE TITLE
'US' country matcher does not work

### ISSUE THREAD

**Issue by chummer80** [gilmoreorless/moment-timezone-data-webpack-plugin#28]
Using:
webpack 4.38.0
moment-timezone 0.5.28
moment-timezone-data-webpack-plugin 1.2.0

Issue:
```javascript
matchCountries: 'US'
```
does not seem to filter out any data, but
```javascript
matchCountries: 'us'
```
does correctly filter out data for timezones outside the US.

For now I'll use `['US', 'us']` in my config

**Comment by chummer80** [comment]
Additional info:

Contrary to my previous plan of using `['US', 'us']`, I will actually go back to using only `'us'`.  This is because including `'US'` seems to cause the same type error that was described in issue #27.

**Comment by gilmoreorless** [comment]
I've released version 1.3.0 which contains a fix for the `'US'` country code (and a few others).

I'm intrigued that you got `matchCountries: 'us'` to work though. When I tried it there were 0 zones added to the data (it filtered out _everything_).

**Comment by chummer80** [comment]
You're right, 'us' only appeared to be working because there was no type error. Sorry for the misinformation and thanks for the fix!
