### ISSUE TITLE
webpack 5 support

### ISSUE THREAD

**Issue by sethomas** [gilmoreorless/moment-timezone-data-webpack-plugin#33]
Using `webpack 5.4.0`, adding this I get the below error:
```
ERROR in NormalModuleFactory.beforeResolve is no longer a waterfall hook, but a bailing hook instead. Do not return the passed object, but modify it instead. Returning false will ignore the request and results in no module created.
```

**Comment by gilmoreorless** [comment]
Hrm that's curious. I'm using webpack's `NormalModuleReplacementPlugin` in a way [described by their documentation](https://webpack.js.org/plugins/normal-module-replacement-plugin/#advanced-example).

I also can't replicate that error message when building the (admittedly very simplified) examples in this repository with webpack 5.4.0.

**Comment by sethomas** [comment]
Ah, tomorrow I'll do better with adding details, sorry for being vague and thanks for the response.

**Comment by sethomas** [comment]
@gilmoreorless very sorry, this must have been due to user error on my end. I am able to use this plugin on my webpack 5.4.0 setup.

**Comment by gilmoreorless** [comment]
Not a problem, thanks for using it!

**Comment by adarsh-drishya** [comment]
update your readme so people know webpack 5 is supported, thanks for this plugin @gilmoreorless

**Comment by adarsh-drishya** [comment]
but this package itself is of 70kb gzip something, does it have any effect? @gilmoreorless

**Comment by gilmoreorless** [comment]
@adarsh-drishya I'm going to be blunt here: What the hell are you talking about?

First of all, the README already explicitly says that webpack 5 is supported.

Then you've added a second question that is:
1. Commenting on a resolved issue from more than 2 years ago.
2. Completely unrelated to the issue.
3. So lacking in context or detail that it's impossible to answer.

If you want answers to questions on an open source project, you can start with respecting the time (and patience) of the people who provide their work for free.
