### ISSUE TITLE
Can we add option to extract timezone data into seperate files?

### ISSUE THREAD

**Issue by web-programmer-here** [gilmoreorless/moment-timezone-data-webpack-plugin#53]
I was testing this plugin and it works great, I am wondering if it is possible to breakdown the timezone data into chunks so I can load them in my webpage separately?

I want to have a js folder that has all the timezone data for individual timezones, for example: 
```
Asia-tokyo.js
Australia.js
```

and this way I can include these in my website via script tag?

**Comment by gilmoreorless** [comment]
I understand your use case, but that's not really what this plugin is designed to do. The plugin is only meant to be a transparent inline filter and replacement when `moment-timezone` requires the `data/packed/latest.json` file. Spitting out a bunch of separate file chunks as a side effect would be a weird thing for a filter to do.

If you're looking to generate those files yourself, I suggest using the [`moment.tz.filterLinkPack()`](https://momentjs.com/timezone/docs/#/data-utilities/filter-link-pack/) utility function to get exactly the data you want. You can look at the internal [`filterData()`](https://github.com/gilmoreorless/moment-timezone-data-webpack-plugin/blob/c60a4633573a1502a7360d7160b5eed627ff839c/src/index.js#L6) function of this plugin as a reference guide — in the end it still [calls `moment.tz.filterLinkPack()` to generate the final data](https://github.com/gilmoreorless/moment-timezone-data-webpack-plugin/blob/c60a4633573a1502a7360d7160b5eed627ff839c/src/index.js#L116-L125).

Also keep in mind that `moment-timezone` is now deprecated and [in maintenance-only mode](https://momentjs.com/docs/#/-project-status/), so I'm pretty hesitant to add any new features to this derivative project.
